//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 03:48:33 PM EAT 
//


package com.honeacademy.petfinder.model.webservice;





public enum AnimalType {


    DOG("Dog"),
    CAT("Cat"),
    SMALL_FURRY("Small&Furry"),
    BARN_YARD("BarnYard"),
    BIRD("Bird"),
    HORSE("Horse"),
    RABBIT("Rabbit"),
    REPTILE("Reptile");
    private final String value;

    AnimalType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AnimalType fromValue(String v) {
        for (AnimalType c: AnimalType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
