//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 03:48:33 PM EAT 
//


package com.honeacademy.petfinder.model.webservice;


import org.simpleframework.xml.Element;
import org.simpleframework.xml.Root;




@Root(name = "header")
public class PetfinderHeaderType {

    @Element(name = "version")
    protected String version;
    @Element(name = "timestamp")
    protected String timestamp;
    @Element(name = "status")
    protected PetfinderHeaderType.Status status;

    /**
     * Gets the value of the version property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the timestamp property.
     *
     * @return possible object is
     * {@link String }
     */
    public String getTimestamp() {
        return timestamp;
    }

    /**
     * Sets the value of the timestamp property.
     *
     * @param value allowed object is
     *              {@link String }
     */
    public void setTimestamp(String value) {
        this.timestamp = value;
    }

    /**
     * Gets the value of the status property.
     *
     * @return possible object is
     * {@link PetfinderHeaderType.Status }
     */
    public PetfinderHeaderType.Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     *
     * @param value allowed object is
     *              {@link PetfinderHeaderType.Status }
     */
    public void setStatus(PetfinderHeaderType.Status value) {
        this.status = value;
    }


    @Root
    public static class Status {

        @Element(name = "code")
        protected Long code;
        @Element(name = "message", required = false)
        protected String message;

        /**
         * Gets the value of the code property.
         *
         * @return possible object is
         * {@link Long }
         */
        public Long getCode() {
            return code;
        }

        /**
         * Sets the value of the code property.
         *
         * @param value allowed object is
         *              {@link Long }
         */
        public void setCode(Long value) {
            this.code = value;
        }

        /**
         * Gets the value of the message property.
         *
         * @return possible object is
         * {@link String }
         */
        public String getMessage() {
            return message;
        }

        /**
         * Sets the value of the message property.
         *
         * @param value allowed object is
         *              {@link String }
         */
        public void setMessage(String value) {
            this.message = value;
        }

    }

}
