//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 03:48:33 PM EAT 
//


package com.honeacademy.petfinder.model.webservice;

import com.squareup.moshi.Json;

import java.util.ArrayList;
import java.util.List;



public class PetfinderShelterRecordList {

    @Json(name="shelter")
    protected List<PetfinderShelterRecord> shelter;

    /**
     * Gets the value of the shelter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the shelter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getShelter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PetfinderShelterRecord }
     * 
     * 
     */
    public List<PetfinderShelterRecord> getShelter() {
        if (shelter == null) {
            shelter = new ArrayList<PetfinderShelterRecord>();
        }
        return this.shelter;
    }

}
