//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 03:48:33 PM EAT 
//


package com.honeacademy.petfinder.model.webservice;

import com.squareup.moshi.Json;


import java.util.ArrayList;
import java.util.List;



public class PetfinderPetIdList {

    @Json(name = "id")
    protected List<Long> id;


    public List<Long> getId() {
        if (id == null) {
            id = new ArrayList<Long>();
        }
        return this.id;
    }

}
