//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.11 at 03:48:33 PM EAT 
//


package com.honeacademy.petfinder.model.webservice;



public enum PetOptionType {

    SPECIAL_NEEDS("specialNeeds"),
    NO_DOGS("noDogs"),
    NO_CATS("noCats"),
    NO_KIDS("noKids"),
    NO_CLAWS("noClaws"),
    HAS_SHOTS("hasShots"),
    HOUSEBROKEN("housebroken"),
    ALTERED("altered");
    private final String value;

    PetOptionType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PetOptionType fromValue(String v) {
        for (PetOptionType c: PetOptionType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
